export const GET_ALL_INSURANCE_COMPANIES_BY_QUERY = "GET_ALL_INSURANCE_COMPANIES_BY_QUERY";
export const ADD_NEW_INSURANCE_COMPANY = 'ADD_NEW_INSURANCE_COMPANY';
export const BIND_INSURANCE_COMPANY = 'BIND_INSURANCE_COMPANY';