export const BIND_GENERAL_IMPORT_INFO = 'BIND_GENERAL_IMPORT_INFO';
export const GET_ALL_GENERAL_IMPOT_BY_QUERY = 'GET_ALL_GENERAL_IMPOT_BY_QUERY';

export const GET_ALL_SUPPLIER_PI = 'GET_ALL_SUPPLIER_PI';
export const GET_ALL_SUPPLIER_PI_DETAILS = 'GET_ALL_SUPPLIER_PI_DETAILS';
export const GET_GENERAL_IMPORT_USED_PI = 'GET_GENERAL_IMPORT_USED_PI';
export const GET_ALL_PROFORMA_INVOICE_FORM_GI = 'GET_ALL_PROFORMA_INVOICE_FORM_GI';
export const BIND_ALL_SUPPLIER_PI_FOR_FILE_GI = 'BIND_ALL_SUPPLIER_PI_FOR_FILE_GI';

export const GET_GENERAL_IMPORT_AMENDMENT = 'GET_GENERAL_IMPORT_AMENDMENT';
