export const GET_ALL_CHARGE_HEADS_BY_QUERY = "GET_ALL_CHARGE_HEADS_BY_QUERY";
export const GET_CHARGE_HEADS_DEOPDOWN = "GET_CHARGE_HEADS_DEOPDOWN";
export const ADD_NEW_CHARGE_HEAD = "ADD_NEW_CHARGE_HEAD";
export const BIND_ALL_CHARGE_HEADS = "BIND_ALL_CHARGE_HEADS";