export const initialBackToBackModel = {
    convertedNumber: "",
    convertionDate: null,
    amendmentDate: null,
    applicationDate: null,
    applicationFormNo: '',

    bbNumber: '',
    bbDate: null,
    bbType: null,
    masterDoc: null,
    beneficiary: null,
    openingBank: '',
    currency: { label: 'USD', value: 'USD' },
    conversionRate: 1.00,
    appliedOnly: false,
    amount: 0,
    payTerm: null,
    maturityFrom: null,
    tenorDays: 0,
    purpose: null,
    latestShipDate: '',
    expiryDate: '',
    expiryPlace: null,
    shippingMark: '',
    advisingBank: null,
    supplier: null,
    supplierPi: null,
    supplierBank: null,
    insuCoverNote: "",
    insuranceCompany: null,
    incoTerms: null,
    nature: null,
    portOfLoading: [],
    portOfDischarge: [],
    tolerance: 0,
    hsCode: [],
    commRef: '',
    remarks: '',
    documentType: { value: 'LC', label: 'LC' },
    docPresentDays: 0,
    isDomestic: false,
    isPartialShipmentAllowed: false,
    isIssuedByTel: false,
    isTransShipment: false,
    isAddConfirmationReq: false,
    isConverted: false,
    isShipped: false,
    status: true,
    isDraft: false,
    files: [],
    fileUrls: [],
    importPI: [],
    supplierPIOrders: []
};