
export const GET_ALL_BRANCHES_BY_QUERY = "GET_ALL_BRANCHES_BY_QUERY";
export const BIND_BRANCHES_BASIC_INFO = "BIND_BRANCHES_BASIC_INFO";
export const GET_BRANCH_BY_BANK = "GET_BRANCH_BY_BANK";
export const BIND_ALL_BRANCHES = 'BIND_ALL_BRANCHES';