export const BIND_FREE_ON_COST_INFO = 'BIND_FREE_ON_COST_INFO';
export const GET_ALL_FREE_ON_COST_BY_QUERY = 'GET_ALL_FREE_ON_COST_BY_QUERY';

export const GET_BB_DOCUMENT_GENERAL_IMPORT_PROFORMA_INVOICE = 'GET_BB_DOCUMENT_GENERAL_IMPORT_PROFORMA_INVOICE';
export const BIND_IMPORT_PI_FROM_MODAL = 'BIND_IMPORT_PI_FROM_MODAL';
export const BIND_ORDER_FROM_MODAL = 'BIND_ORDER_FROM_MODAL';
export const BIND_ALL_PI_FROM_BB_GI = 'BIND_ALL_PI_FROM_BB_GI';

export const BIND_QUANTITY_AND_AMOUNT = 'BIND_QUANTITY_AND_AMOUNT';
export const GET_FOC_INVOICES_ORDER_LIST = 'GET_FOC_INVOICES_ORDER_LIST';

export const BIND_ALL_ORDER_FROM_FOC_INVOICES = 'BIND_ALL_ORDER_FROM_FOC_INVOICES';

export const GET_FOC_INVOICES_ORDER_LIST_FOR_MISCELLANEOUS = 'GET_FOC_INVOICES_ORDER_LIST_FOR_MISCELLANEOUS';
export const BIND_ALL_ORDER_FROM_FOC_INVOICES_FOR_MISCELLANEOUS = 'BIND_ALL_ORDER_FROM_FOC_INVOICES_FOR_MISCELLANEOUS';

export const GET_ALL_USED_FOC_INVOICES = 'GET_ALL_USED_FOC_INVOICES';
