
export const BIND_DOCUMENT_SUBMISSION_INFO = 'BIND_DOCUMENT_SUBMISSION_INFO';

export const GET_ALL_DOCUMENT_SUBMISSION_BY_QUERY = 'GET_ALL_DOCUMENT_SUBMISSION_BY_QUERY';

export const BIND_ALL_EXPOR_INVOICES = 'BIND_ALL_EXPOR_INVOICES';
export const BIND_MODAL_EXPORT_INVOICES = 'BIND_MODAL_EXPORT_INVOICES';
export const BIND_ALL_EXPORT_INVOICES_FOR_TABLE = 'BIND_ALL_EXPORT_INVOICES_FOR_TABLE';


export const GET_ALL_USED_EXPORT_INVOICES = 'GET_ALL_USED_EXPORT_INVOICES';
