export const initialUdModel = {
    bgmeaName: 'Bangladesh Garment Manufactures & Exporters Association (BGMEA)',
    bgmeaAddress: 'BGMEA Bhaban (Level-4 & 5) 669/E, Jhautala Road (Near CNG Station), South Khulshi, Chattogram, Bangladesh',
    applicationNo: '',
    applicationDate: '',
    udNo: '',
    trackingNo: '',
    udDate: '',
    udVersion: 0,
    beneficiary: null,
    bondLicense: '',
    licenseDate: '',
    vatRegistration: '',
    regDate: '',
    membershipNo: '',
    membershipYear: 0,
    buyer: null,
    lienBank: null,
    masterDoc: [],
    masterDocAmount: 0,
    files: [],
    fileUrls: [],
    amendmentDate: '',
    amendmentTrackingNumber: '',
    amendmentRefNumber: '',
    amendmentDocumentNumber: '',
    isMissingValueAllowed: false
};