
export const BIND_COUNTRY_PLACE_BASIC_INFO = "BIND_COUNTRY_PLACE_BASIC_INFO";
export const BIND_COUNTRY_DDL = "BIND_COUNTRY_DDL";
export const GET_ALL_PLACES_BY_QUERY = "GET_ALL_PLACES_BY_QUERY";
export const GET_ALL_PLACES_BY_COUNTRY = "GET_ALL_PLACES_BY_COUNTRY";

export const BIND_ALL_COUNTRY_PLACES = "BIND_ALL_COUNTRY_PLACES";
export const BIND_COUNTRY_PLACES_BY_COUNTRY = "BIND_COUNTRY_PLACES_BY_COUNTRY";
export const UPDATE_COUNTRY_PLACES = "UPDATE_COUNTRY_PLACES";

export const RESET_COUNTRY_PLACES_STATE = "RESET_COUNTRY_PLACES_STATE";
export const DELETE_COUNTRY_PLACES = "DELETE_COUNTRY_PLACES";
