export const initialExportInvoice = {
    invoiceNo: '',
    invoiceDate: '',
    expNo: '',
    expDate: '',
    billNo: '',
    billDate: '',
    beneficiary: null,
    manufacturerBank: null,
    bookingRefNo: '',
    masterDoc: null,
    contractDate: '',
    applicant: null,
    buyerBank: null,
    notifyParties: [],
    shipmentMode: null,
    preCarrier: '',
    containerNo: '',
    portOfLoading: null,
    portOfDischarge: null,
    finalDestination: null,
    sailingOn: '',
    incoterm: null,
    incotermPlace: null,
    vessel: '',
    voyage: '',
    payTerm: null,
    maturityForm: null,
    tenorDay: 0,
    frightLPaymentMode: '',
    originCountry: { label: 'Bangladesh', value: 'Bangladesh' },
    sealNo: '',
    files: [],
    fileUrls: [],
    isDraft: false,
    totalInvoiceAmount: 0
};

export const initialModelForMasterDocElements = {
    portOfLoading: [],
    portOfDischarge: [],
    finalDestination: []
};