export const initialDocumentSubmissionModel = {
    submissionDate: '',
    submissionRefNumber: '',
    bookingRefNo: '',
    comRef: '',
    bookingRefDate: '',
    currency: { label: 'USD', value: 'USD' },
    conversionRate: 1.00,
    submissionTo: '',
    submissionType: '',
    submissionBank: null,
    bankRefNumber: '',
    bankRefDate: '',
    beneficiary: null,
    negotiationDate: '',
    dayToRealize: 0,
    blNo: '',
    blDate: '',
    realizationDate: '',
    docDispatchDate: '',
    courierCompany: null,
    receiptNo: '',
    totalInvoiceValue: 0,
    notYetFinal: false,
    showPendingInvoice: false,
    masterDoc: null,
    exportInvoice: [],
    isDraft: false,
    files: [],
    fileUrls: []

};