export const BIND_EXPORT_INVOICE_INFO = 'BIND_EXPORT_INVOICE_INFO';
export const BIND_MISTER_DOC_INFO = 'BIND_MISTER_DOC_INFO';
export const GET_ALL_NOTIFY_PARTIES = 'GET_ALL_NOTIFY_PARTIES';

export const GET_ALL_EXPORT_INVOICES_BY_QUERY = 'GET_ALL_EXPORT_INVOICES_BY_QUERY';
// export const GET_ALL_PACKAGING_LIST = 'GET_ALL_PACKAGING_LIST';

export const BIND_MODAL_PACKAGING_LIST = 'BIND_MODAL_PACKAGING_LIST';
export const BIND_PACKAGING_LIST = 'BIND_PACKAGING_LIST';
export const GET_ALL_USED_PACKAGING_LIST = 'GET_ALL_USED_PACKAGING_LIST';
export const BIND_PACKAGING_DETAILS = 'BIND_PACKAGING_DETAILS';