

export const GET_ALL_MASTER_DOCUMENTS_BY_QUERY = "GET_ALL_MASTER_DOCUMENTS_BY_QUERY";
export const BIND_MASTER_DOC_INFO = "BIND_MASTER_DOC_INFO";
export const MASTER_DOC_DATA_ON_PROGRESS = "MASTER_DOC_DATA_ON_PROGRESS";
export const BIND_EXPORT_PI_BUYER_PO = "BIND_EXPORT_PI_BUYER_PO";
export const BIND_USED_EXPORT_PI = 'BIND_USED_EXPORT_PI';


///FOR TRANSFER///
export const BIND_TRANSFERABLE_LIST = 'BIND_TRANSFERABLE_LIST';
export const BIND_TRANSFERABLE_MASTER_DOCUMENT_PO = 'BIND_TRANSFERABLE_MASTER_DOCUMENT_PO';
export const BIND_MASTER_DOCUMENT_TRANSFERABLE = 'BIND_MASTER_DOCUMENT_TRANSFERABLE';
export const BIND_REMOVABLE_QTY = 'BIND_REMOVABLE_QTY';
/////////////////

//FOR AMENDMENTS//

export const BIND_MASTER_DOCUMENT_FOR_AMENDMENTS = 'BIND_MASTER_DOCUMENT_FOR_AMENDMENTS';
export const GET_MASTER_AMENDMENT = 'GET_MASTER_AMENDMENT';
export const CLEAR_MASTER_DOCUMENT_FOR_AMENDMENTS = 'CLEAR_MASTER_DOCUMENT_FOR_AMENDMENTS';
export const BIND_ALL_PO_AMENDMENT = 'BIND_ALL_PO_AMENDMENT';


//FOR CONVERSION

export const GET_BUYER_PO_FOR_CONVERTION = 'GET_BUYER_PO_FOR_CONVERTIONSS';

export const GET_BACK_TO_BACK_DOCUMENTS = 'GET_BACK_TO_BACK_DOCUMENTS';

export const GET_ALL_EXPORT_PI_FOR_LIST = 'GET_ALL_EXPORT_PI_FOR_LIST';
export const GET_ALL_USED_EXPORT_PI = 'GET_ALL_USED_EXPORT_PI';
export const GET_ALL_ORDER_ID = 'GET_ALL_ORDER_ID';
