
export const GET_ALL_BANKS_BY_QUERY = "GET_ALL_BANKS_BY_QUERY";
export const BIND_ALL_BANKS = "BIND_ALL_BANKS";
export const BIND_BANK_BASIC_INFO = "BIND_BANK_BASIC_INFO";
export const BIND_CHARGE_HEADS = "BIND_CHARGE_HEADS";
