
//import section
export const BIND_ALL_IMPORT_SCHEDULE_INFO = 'BIND_ALL_IMPORT_SCHEDULE_INFO';
export const BIND_ALL_IMPORT_SCHEDULE_DETAILS = 'BIND_ALL_IMPORT_SCHEDULE_DETAILS';
export const GET_ALL_IMPORT_SCHEDULE_BY_QUERY = 'GET_ALL_IMPORT_SCHEDULE_BY_QUERY';


//export section
export const BIND_ALL_EXPORT_SCHEDULE_INFO = 'BIND_ALL_EXPORT_SCHEDULE_INFO';
export const GET_ALL_EXPORT_SCHEDULE_BY_QUERY = 'GET_ALL_EXPORT_SCHEDULE_BY_QUERY';
export const BIND_ALL_EXPORT_SCHEDULE_DETAILS = 'BIND_ALL_EXPORT_SCHEDULE_DETAILS';

export const BIND_MASTER_DOC_ELEMENT = 'BIND_MASTER_DOC_ELEMENT';
export const BIND_BACK_TO_BACK_ELEMENT = 'BIND_BACK_TO_BACK_ELEMENT';
