// export const STORED_LC = "STORED_LC";

export const GET_ALL_MASTER_DOCUMENT_GROUPS_BY_QUERY = "GET_ALL_MASTER_DOCUMENT_GROUPS_BY_QUERY";
export const BIND_GROUP_LC_BASIC_INFO = "BIND_GROUP_LC_BASIC_INFO";
export const BIND_GROUP_LC_BASIC_INFO_LIST = "BIND_GROUP_LC_BASIC_INFO_LIST";
// export const BIND_MODAL_GROUP_LC_BASIC_INFO_LIST = "BIND_MODAL_GROUP_LC_BASIC_INFO_LIST";
export const GET_MASTER_DOCUMENTS_FOR_GROUP = "GET_MASTER_DOCUMENTS_FOR_GROUP";
export const BIND_ALL_GROUPLIST = 'BIND_ALL_GROUPLIST';