export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_AUTHENTICATE_USER = 'GET_AUTHENTICATE_USER';
export const GET_AUTHENTICATE_USER_PERMISSION = 'GET_AUTHENTICATE_USER_PERMISSION';

export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';

export const AUTH_TOKEN_STORE = 'AUTH_TOKEN_STORE';


export const FILE_PROGRESS = 'FILE_PROGRESS';

export const GET_PROGRESS = "GET_PROGRESS";
export const POST_PROGRESS = "POST_PROGRESS";
export const IS_OPEN_INSTANT_LOGIN_MODAL = "IS_OPEN_INSTANT_LOGIN_MODAL";

export const SESSION_DURATION = "SESSION_DURATION";


export const BIND_AUTH_NAVIGATION = "BIND_AUTH_NAVIGATION";

export const BIND_USER_TENANT = "BIND_USER_TENANT";

export const BIND_DEFAULT_TENANT = "BIND_DEFAULT_TENANT";

///For Common Reducers
export const GET_BUYER_DROPDOWN_CM = "GET_BUYER_DROPDOWN_CM";

export const GET_BUYER_PO_DROPDOWN_CM = "GET_BUYER_PO_DROPDOWN_CM";
export const GET_COST_HEAD_DROPDOWN = "GET_COST_HEAD_DROPDOWN";


export const GET_CHARGE_HEAD_DROPDOWN = "GET_CHARGE_HEAD_DROPDOWN";
export const EXPORT_PI_DROPDOWN = "EXPORT_PI_DROPDOWN";

export const GET_BANKS_DROPDOWN = "GET_BANKS_DROPDOWN";

export const GET_BRANCHES_DROPDOWN = "GET_BRANCHES_DROPDOWN";
export const GET_CURRENCY_DROPDOWN_CM = "GET_CURRENCY_DROPDOWN_CM";

export const GET_INCO_TERMS_DROPDOWN_CM = 'GET_INCO_TERMS_DROPDOWN_CM';
export const GET_PARTY_DROPDOWN_CM = "GET_PARTY_DROPDOWN_CM";
export const GET_COUNTRY_PLACE_DROPDOWN_CM = 'GET_COUNTRY_PLACE_DROPDOWN_CM';
export const GET_INSURANCE_COMPANY_DROPDOWN_CM = 'GET_INSURANCE_COMPANY_DROPDOWN_CM';
export const GET_SUPPLIER_DROPDOWN_CM = 'GET_SUPPLIER_DROPDOWN_CM';
export const GET_ALL_IMPORT_PI_CM = 'GET_ALL_IMPORT_PI_CM';
export const GET_ALL_MASTER_DOCUMENTS_BY_QUERY_CM = 'GET_ALL_MASTER_DOCUMENTS_BY_QUERY_CM';

export const GET_MASTER_DOCUMENT_BY_BUYER_CM = 'GET_MASTER_DOCUMENT_BY_BUYER_CM';

export const BACK_TO_BACK_DROPDOWN_CM = 'BACK_TO_BACK_DROPDOWN_CM';


///
export const IS_DATA_LOADED_CM = "IS_DATA_LOADED_CM";
export const IS_DATA_PROGRESS_CM = "IS_DATA_PROGRESS_CM";
export const IS_DATA_SUBMIT_PROGRESS_CM = "IS_DATA_SUBMIT_PROGRESS_CM";
export const IS_FILE_UPLOADED_COMPLETE = "IS_FILE_UPLOADED_COMPLETE";

//
export const GET_TENANT_DROPDOWN_CM = "GET_TENANT_DROPDOWN_CM";
export const GET_HS_CODE_DROPDOWN_CM = "GET_HS_CODE_DROPDOWN_CM";

//
///Caching
export const BIND_STYLE_INFO_CACHE = "BIND_STYLE_INFO_CACHE";
export const BIND_STYLE_SETTINGS_CACHE = "BIND_STYLE_SETTINGS_CACHE";
export const BIND_REMOVABLE_QTY_CACHE = "BIND_REMOVABLE_QTY_CACHE";
export const GET_TENANT_DROPDOWN_CM_CACHE = "GET_TENANT_DROPDOWN_CM_CACHE";


export const GET_ALL_MASTER_DOCUMENT_DROPDOWN = 'GET_ALL_MASTER_DOCUMENT_DROPDOWN';

export const GET_ALL_BANK_ACCOUNT = 'GET_ALL_BANK_ACCOUNT';
export const GET_ALL_BANK_ACCOUNT_BY_BANK = 'GET_ALL_BANK_ACCOUNT_BY_BANK';
export const GET_ALL_BANK_CHARGE_HEAD = 'GET_ALL_BANK_CHARGE_HEAD';

export const GET_ALL_MASTER_DOC_AND_BACK_TO_BACK_DOCUMENT = 'GET_ALL_MASTER_DOC_AND_BACK_TO_BACK_DOCUMENT';

export const GET_ALL_CNF_TRANSPORT_DROPDOWN_CM = 'GET_ALL_CNF_TRANSPORT_DROPDOWN_CM';

export const GET_ALL_FOC_INVOICES_DROPDOWN_CM = 'GET_ALL_FOC_INVOICES_DROPDOWN_CM';

export const GET_MASTER_DOCUMENT_GROUP_DROPDOWN_CM = 'GET_MASTER_DOCUMENT_GROUP_DROPDOWN_CM';
export const GET_BANK_ACCOUNT_TYPES = 'GET_BANK_ACCOUNT_TYPES';
export const GET_ALL_COURIER_COMPANY_DROPDOWN_CM = 'GET_ALL_COURIER_COMPANY_DROPDOWN_CM';

export const GET_GENERAL_IMPORT_DROPDOWN_CM = 'GET_GENERAL_IMPORT_DROPDOWN_CM';
export const GET_FOC_DROPDOWN_CM = 'GET_FOC_DROPDOWN_CM';
export const GET_EXPORT_INVOICE_DROPDOWN_CM = 'GET_EXPORT_INVOICE_DROPDOWN_CM';
