export const GET_ALL_COST_HEADS_BY_QUERY = "GET_ALL_COST_HEADS_BY_QUERY";
export const GET_COST_HEAD_DROPDOWN_BY_ID = "GET_COST_HEAD_DROPDOWN_BY_ID";
export const BIND_COST_HEADS = "BIND_COST_HEADS";


///

export const IS_DATA_COST_HEADS_LOADED = "IS_DATA_COST_HEADS_LOADED";
export const IS_DATA_COST_HEADS_PROGRESS = "IS_DATA_COST_HEADS_PROGRESS";
export const IS_DATA_COST_HEADS_SUBMIT_PROGRESS = "IS_DATA_COST_HEADS_SUBMIT_PROGRESS";