
export const initialEdfModel = {
    exporter: null,
    commercialReference: '',
    supplier: null,
    openingBank: null,
    importInvoice: null,
    bankBranch: null,
    loanAmount: 0,
    supplierPayDate: '',
    edfReceiveDate: '',
    targetRepayDate: '',
    isRepaid: true,
    adPayDate: '',
    adRepayDate: '',
    bbPayDate: '',
    bbRepayDate: '',
    adLoanDuration: 0,
    bbLoanDuration: 0,
    bankLoanDuration: 0,
    bankInterestRate: 0,
    bankInterestRateAmount: 0,
    adInterestRate: 0,
    adInterestAmount: 0,
    bbInterestRate: 0,
    bbInterestAmount: 0,
    totalAmount: 0,
    adRefNumber: '',
    bbRefNumber: '',
    branchInterestAmount: 0,
    currency: null,
    conversionRate: 0,
    files: [],
    fileUrls: []

};