export const initialFocModel = {
    // convertedNumber: "",
    // convertionDate: null,
    // amendmentDate: null,
    documentDate: '',
    commRef: '',
    supplier: null,
    verifyBank: null,
    documentNumber: '',
    referenceType: null,
    masterDocument: [],
    document: [],
    supplierPi: null,
    // backToBackType: null,
    currency: { label: 'USD', value: 'USD' },
    conversionRate: 1.00,
    beneficiary: null,
    amount: 0,
    sourceType: null,
    purpose: null,
    latestShipDate: '',
    expiryDate: null,
    incotermPlace: null,
    shippingMark: '',
    insuCoverNote: "",
    insuranceCompany: null,
    incoTerms: null,
    masterDoc: [],
    nature: null,
    portOfLoading: [],
    portOfDischarge: [],
    tolerance: 0,
    hsCode: [],
    remarks: '',
    docPresentDays: 0,
    isDomestic: false,
    isPartialShipmentAllowed: false,
    isIssuedByTel: false,
    isTransShipment: false,
    isAddConfirmationReq: false,
    status: true,
    // isConverted: false,
    isShipped: false,
    isDraft: false,
    files: [],
    fileUrls: [],
    importPI: [],
    supplierPIOrders: []
};
