export const initialGeneralImportModel = {
    convertedNumber: "",
    convertionDate: null,
    amendmentDate: null,
    applicationDate: null,
    applicationFormNo: '',
    backToBackNumber: '',
    backToBackDate: null,
    // backToBackType: null,
    currency: { label: 'USD', value: 'USD' },
    conversionRate: 1.00,
    beneficiary: null,
    openingBank: null,
    appliedOnly: false,
    amount: 0,
    sourceType: null,
    payTerm: null,
    maturityFrom: null,
    tenorDays: 0,
    purpose: null,
    latestShipDate: null,
    expiryDate: null,
    expiryPlace: null,
    shippingMark: '',
    advisingBank: null,
    supplier: null,
    supplierPi: null,
    supplierBank: null,
    insuCoverNote: "",
    insuranceCompany: null,
    incoTerms: null,
    nature: null,
    portOfLoading: [],
    portOfDischarge: [],
    tolerance: 0,
    hsCode: [],
    commRef: '',
    remarks: '',
    documentType: { value: 'LC', label: 'LC' },
    docPresentDays: 0,
    isDomestic: false,
    isPartialShipmentAllowed: false,
    isIssuedByTel: false,
    isTransShipment: false,
    isAddConfirmationReq: false,
    status: true,
    isConverted: false,
    isShipped: false,
    isDraft: false,
    files: [],
    fileUrls: [],
    importPI: [],
    supplierPIOrders: []
};