

export const BIND_COMMERCIAL_INVOICE_INFO = 'BIND_COMMERCIAL_INVOICE_INFO';
export const GET_ALL_COMMERCIAL_INVOICE_BY_QUERY = 'GET_ALL_COMMERCIAL_INVOICE_BY_QUERY';

export const BIND_BACK_TO_BACK_INFORMATION_FOR_INVOICE = 'BIND_BACK_TO_BACK_INFORMATION_FOR_INVOICE';