export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const GET_DOCUMENT = "GET_DOCUMENT";
export const BIND_DOCUMENT = "BIND_DOCUMENT";
export const GET_DOCUMENT_BY_ID = "GET_DOCUMENT_BY_ID";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

export const GET_MASTER_AND_BACK_TO_BACK_DOCUMENT_NUMBER = 'GET_MASTER_AND_BACK_TO_BACK_DOCUMENT_NUMBER';
export const BIND_ALL_DOCUMENT_INFO = 'BIND_ALL_DOCUMENT_INFO';
export const GET_FILE_BY_TYPE_AND_MASTER_DOCUMENT_ID = 'GET_FILE_BY_TYPE_AND_MASTER_DOCUMENT_ID';