
export const GET_ALL_ACCOUNTS_BY_QUERY = 'GET_ALL_ACCOUNTS_BY_QUERY';
export const BIND_ALL_ACCOUNTS_BASIC_INFO = 'BIND_ALL_ACCOUNTS_BASIC_INFO';
export const GET_ACCOUNT_BY_BANK_BRANCH = 'GET_ACCOUNT_BY_BANK_BRANCH';