export const BIND_ALL_AGENT_INFO = 'BIND_ALL_AGENT_INFO';
export const AGENT_IMAGE_UPLOADING = "AGENT_IMAGE_UPLOADING";

export const GET_ALL_AGENT_BY_QUERY = "GET_ALL_AGENT_BY_QUERY";
export const GET_ALL_AGENT_BY_STATUS = "GET_ALL_AGENT_BY_STATUS";