export const BIND_BB_FORM_INFO = 'BIND_BB_FORM_INFO';

export const GET_ALL_IMPORT_PI = 'GET_ALL_IMPORT_PI';

export const BIND_ALL_SUPPLIER_PI = 'BIND_ALL_SUPPLIER_PI';
export const GET_ALL_BB_DOCUMENTS_BY_QUERY = 'GET_ALL_BB_DOCUMENTS_BY_QUERY';

export const GET_USED_IPI = 'GET_USED_IPI';

export const GET_BACK_TO_BACK_AMENDMENT = 'GET_BACK_TO_BACK_AMENDMENT';

export const GET_ALL_PROFORMA_INVOICE = 'GET_ALL_ALL_PROFORMA_INVOICE';
export const BIND_ALL_SUPPLIER_PI_FOR_FILE = 'BIND_ALL_SUPPLIER_PI_FOR_FILE';

export const GET_ALL_USED_PI = 'GET_ALL_ALL_USED_PI';