export const BIND_CHARGE_HEAD_ADVICE = 'BIND_CHARGE_HEAD_ADVICE';
export const BIND_CHARGE_ADVICE_DETAILS = 'BIND_CHARGE_ADVICE_DETAILS';

export const GET_ALL_BANK_CHARGE_ADVICE_BY_QUERY = 'GET_ALL_BANK_CHARGE_ADVICE_BY_QUERY';
export const GET_ALL_ACCOUNT_BY_BRANCH = 'GET_ALL_ACCOUNT_BY_BRANCH';