
export const BIND_PAYMENT_REALIZATION_INFO = 'BIND_PAYMENT_REALIZATION_INFO';
export const BIND_DISTRIBUTION_AND_DEDUCTION_INFO = 'BIND_DISTRIBUTION_AND_DEDUCTION_INFO';

export const BIND_EXPORT_INVOICE_FOR_LIST = 'BIND_EXPORT_INVOICE_FOR_LIST';
export const BIND_EXPORT_INVOICE_FOR_MODAL = 'BIND_EXPORT_INVOICE_FOR_MODAL';

export const GET_ALL_PAYMENT_REALIZATIONS_BY_QUERY = 'GET_ALL_PAYMENT_REALIZATIONS_BY_QUERY';
export const GET_MODAL_EXPORT_INVOICES_BY_QUERY = 'GET_MODAL_EXPORT_INVOICES_BY_QUERY';
