export const BIND_UTILIZATION_DECLARATION_INFO = 'BIND_UTILIZATION_DECLARATION_INFO';
export const GET_ALL_UD_BY_QUERY = 'GET_ALL_UD_BY_QUERY';

export const BIND_MASTER_DOCUMENTS_FROM_MODAL = 'BIND_MASTER_DOCUMENTS_FROM_MODAL';
export const GET_NOTIFY_PARTIES = 'GET_NOTIFY_PARTIES';
export const GET_MASTER_DOCUMENTS_FROM_GROUP = 'GET_MASTER_DOCUMENTS_FROM_GROUP';
export const GET_BACK_TO_BACK_DOCUMENTS = 'GET_BACK_TO_BACK_DOCUMENTS';
export const BIND_BACK_TO_BACK_DOCUMENTS = 'BIND_BACK_TO_BACK_DOCUMENTS';

export const BIND_UD_AMENDMENTS = 'BIND_UD_AMENDMENTS';
export const BIND_All_BACK_TO_BACK_FOR_MODAL = 'BIND_All_BACK_TO_BACK_FOR_MODAL';
export const BIND_ALL_MASTER_DOC_GROUP_DATA_FOR_MODAL = 'BIND_ALL_MASTER_DOC_GROUP_DATA_FOR_MODAL';

export const BIND_OLD_UD_INFO = 'BIND_OLD_UD_INFO';
export const BIND_OLD_BACK_TO_BACK = 'BIND_OLD_BACK_TO_BACK';
export const BIND_OLD_MASTER_DOCUMENT = 'BIND_OLD_MASTER_DOCUMENT';

export const GET_ALL_USED_MASTER_DOCUMENTS = 'GET_ALL_USED_MASTER_DOCUMENTS';